export const queryKeys = {
  auth: {
    all: ["auth"] as const,
    user: () => [...queryKeys.auth.all, "user"] as const,
  },
  products: {
    all: ["products"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.products.all, "list", params] as const,
    detail: (id: string) => [...queryKeys.products.all, "detail", id] as const,
    overview: () => [...queryKeys.products.all, "overview"] as const,
    categories: () => [...queryKeys.products.all, "categories"] as const,
    discounts: () => [...queryKeys.products.all, "discounts"] as const,
    history: (id: string, params?: Record<string, unknown>) => [...queryKeys.products.all, "history", id, params] as const,
  },
  customers: {
    all: ["customers"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.customers.all, "list", params] as const,
    detail: (id: string) => [...queryKeys.customers.all, "detail", id] as const,
    purchases: (id: string, params?: Record<string, unknown>) => [...queryKeys.customers.all, "purchases", id, params] as const,
    pointsLedger: (id: string, params?: Record<string, unknown>) => [...queryKeys.customers.all, "pointsLedger", id, params] as const,
  },
  vendors: {
    all: ["vendors"] as const,
    list: () => [...queryKeys.vendors.all, "list"] as const,
    detail: (id: string) => [...queryKeys.vendors.all, "detail", id] as const,
    purchaseOrders: (vendorId: string) => [...queryKeys.vendors.all, "purchaseOrders", vendorId] as const,
    bills: (vendorId: string, status?: string) => [...queryKeys.vendors.all, "bills", vendorId, status] as const,
    bill: (vendorId: string, billId: string) => [...queryKeys.vendors.all, "bill", vendorId, billId] as const,
    overview: (vendorId: string) => [...queryKeys.vendors.all, "overview", vendorId] as const,
    statement: (vendorId: string) => [...queryKeys.vendors.all, "statement", vendorId] as const,
    outstandingBills: () => [...queryKeys.vendors.all, "outstandingBills"] as const,
    ledgerImports: (vendorId: string) => [...queryKeys.vendors.all, "ledgerImports", vendorId] as const,
  },
  orders: {
    all: ["orders"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.orders.all, "list", params] as const,
    detail: (id: string) => [...queryKeys.orders.all, "detail", id] as const,
    overview: (params?: Record<string, unknown>) => [...queryKeys.orders.all, "overview", params] as const,
  },
  expenses: {
    all: ["expenses"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.expenses.all, "list", params] as const,
    summary: (params?: Record<string, unknown>) => [...queryKeys.expenses.all, "summary", params] as const,
  },
  discounts: {
    all: ["discounts"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.discounts.all, "list", params] as const,
    detail: (id: string) => [...queryKeys.discounts.all, "detail", id] as const,
    overview: (params?: Record<string, unknown>) => [...queryKeys.discounts.all, "overview", params] as const,
    products: (id: string, params?: Record<string, unknown>) => [...queryKeys.discounts.all, "products", id, params] as const,
  },
  promoCodes: {
    all: ["promoCodes"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.promoCodes.all, "list", params] as const,
    detail: (id: string) => [...queryKeys.promoCodes.all, "detail", id] as const,
  },
  users: {
    all: ["users"] as const,
    list: (params?: Record<string, unknown>) => [...queryKeys.users.all, "list", params] as const,
  },
  reports: {
    all: ["reports"] as const,
    cashLedger: (params?: Record<string, unknown>) => [...queryKeys.reports.all, "cashLedger", params] as const,
    overview: (params?: Record<string, unknown>) => [...queryKeys.reports.all, "overview", params] as const,
    cashPosition: (params?: Record<string, unknown>) => [...queryKeys.reports.all, "cashPosition", params] as const,
    netPosition: (params?: Record<string, unknown>) => [...queryKeys.reports.all, "netPosition", params] as const,
    workingCapital: () => [...queryKeys.reports.all, "workingCapital"] as const,
    equity: (params?: Record<string, unknown>) => [...queryKeys.reports.all, "equity", params] as const,
    runway: (lookbackDays?: number) => [...queryKeys.reports.all, "runway", lookbackDays] as const,
    breakEven: (lookbackDays?: number) => [...queryKeys.reports.all, "breakEven", lookbackDays] as const,
    profitAndLoss: (params?: Record<string, unknown>) => [...queryKeys.reports.all, "pnl", params] as const,
    profitability: (params?: Record<string, unknown>) => [...queryKeys.reports.all, "profitability", params] as const,
    dailySummary: (params?: Record<string, unknown>) => [...queryKeys.reports.all, "dailySummary", params] as const,
    paymentMethods: (params?: Record<string, unknown>) => [...queryKeys.reports.all, "paymentMethods", params] as const,
    locations: () => [...queryKeys.reports.all, "locations"] as const,
    refundAnomalies: (params?: Record<string, unknown>) => [...queryKeys.reports.all, "refundAnomalies", params] as const,
    discountAnomalies: (params?: Record<string, unknown>) => [...queryKeys.reports.all, "discountAnomalies", params] as const,
    anomalyThresholds: () => [...queryKeys.reports.all, "anomalyThresholds"] as const,
    budgetStatus: (monthStart: string) => [...queryKeys.reports.all, "budgetStatus", monthStart] as const,
    budgets: () => [...queryKeys.reports.all, "budgets"] as const,
    customerCreditRisk: (customerId?: string) => [...queryKeys.reports.all, "customerCreditRisk", customerId] as const,
    debtDriftCheck: () => [...queryKeys.reports.all, "debtDriftCheck"] as const,
  },
  pos: {
    all: ["pos"] as const,
    cart: () => [...queryKeys.pos.all, "cart"] as const,
    products: (params?: Record<string, unknown>) => [...queryKeys.pos.all, "products", params] as const,
    categories: () => [...queryKeys.pos.all, "categories"] as const,
  },
  budget: {
    all: ["budget"] as const,
    status: (monthStart: string) => [...queryKeys.budget.all, "status", monthStart] as const,
    list: () => [...queryKeys.budget.all, "list"] as const,
  },
  storeCredit: {
    all: ["storeCredit"] as const,
    pool: () => [...queryKeys.storeCredit.all, "pool"] as const,
    poolHistory: () => [...queryKeys.storeCredit.all, "poolHistory"] as const,
    poolOverview: () => [...queryKeys.storeCredit.all, "poolOverview"] as const,
    customerBalance: (id: string) => [...queryKeys.storeCredit.all, "customerBalance", id] as const,
    customerHistory: (id: string, params?: Record<string, unknown>) => [...queryKeys.storeCredit.all, "customerHistory", id, params] as const,
  },
  reconciliation: {
    all: ["reconciliation"] as const,
    externalTransactions: (status?: string) => [...queryKeys.reconciliation.all, "externalTransactions", status] as const,
    unmatched: () => [...queryKeys.reconciliation.all, "unmatched"] as const,
  },
};
